<?php
/**
 * Template Name: Customer Portal
 * description: >-
 * Customer Portal Template
 * @package  uwd_wp_theme
 */

get_header();
?>
<div class="wrap">
	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">
			<div id="wp-vue-app">
				This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in WordPress.
			</div><!-- #vue-app -->
		</main><!-- #main -->
	</div><!-- #primary -->
</div><!-- .wrap -->
