import Vue from "vue";
import Vuex from "vuex";
import Axios from "axios";
import VueAxios from "vue-axios";

Vue.use(Vuex);
Vue.use(VueAxios, Axios);

Vue.axios.defaults.baseURL = "https://aaronbeach.pythonanywhere.com/";

export default new Vuex.Store({
  state: {
    logged: true,
    customer: {},
    projects: [],
    services: [
      {
        id: "45473",
        lds_id: "214403",
        cst_id: "4113",
        ils_id: "93670",
        contractid: "373474",
        productid: "Door",
        GrossAmount: "11400.0000",
        jbs_id: "C",
        brp_id: "CLE  ",
        pds_id: "CLE",
        cmt_id: "G",
        Commission: "179.3300",
        ins_installer1: "261",
        ins_installer2: "0",
        measuredby: "201",
        ContractDate: "2018-04-21 00:00:00",
        CancelDate: null,
        HoldDate: null,
        hld_id: " ",
        mls_id: "9",
        slr_id: "875",
        slr_id2: "0",
        slr_split: "0",
        fns_id: " ",
        fns_id2: " ",
        fns_id3: " ",
        ProductID2: "",
        ProductID3: "",
        ProductID4: "",
        pws_id: "R",
        vnd_id: "0",
        vnd_id2: "0",
        vnd_id3: "0",
        vnd_id4: "0",
        GrossBatched: "0.0000",
        BatchFlag: "0",
        GrossBatched2: "0.0000",
        BatchFlag2: "0",
        StatusDate: "2018-08-02 00:00:00",
        BudgetCost: "0.0000",
        ActualCost: "0.0000",
        FundedDate: null,
        FundedAmount: "0.0000",
        ParAmount: "0.0500",
        FinCo_ID: "2",
        FinAmount: "7400.0000",
        FinMonths: "36",
        FinCrLimit: "9500.0000",
        FinPlan_ID: "7",
        FinApproved: "1",
        FinRate: "0",
        FinTerms: "36",
        FinExpire: null,
        FinFee: "0.0000",
        FinHomeValue: "0.0000",
        FinParty1Employer: "",
        FinParty1Income: "0.0000",
        FinParty1CreditScore: "0",
        FinParty1Name: "Pavlli",
        FinParty1EmpPhone: "",
        FinParty2Employer: "",
        FinParty2Income: "0.0000",
        FinParty2CreditScore: "0",
        FinParty2Name: "",
        FinParty2EmpPhone: "",
        FinDtApproved: "2018-04-23 00:00:00",
        job_user_1: null,
        job_user_2: "2100.00",
        job_user_3: null,
        job_user_4: null,
        job_user_5: "",
        job_user_6: null,
        job_user_7: null,
        job_user_8: null,
        job_user_9: null,
        job_user_10: null,
        job_user_11: null,
        job_user_12: null,
        job_user_13: null,
        job_user_14: null,
        job_user_15: null,
        job_user_16: "56",
        job_user_17: "40",
        job_user_18: "0",
        job_user_19: "0",
        job_user_20: null,
        LastModifiedBy: "2196",
        LastModifiedOn: "2018-10-09 16:40:18",
        USN: "43",
        JobNotes: "",
        FinNotes: "5774422413469494\r\n4091",
        QBJobRefID: null,
        QBJobDate: null,
        QBJobBalance: null,
        ins_installer3: "0",
        ins_installer4: "0",
        JobNetAmt: "0.0000",
        nmp_descr: "Mr.",
        firstname: "Pavlli",
        lastname: "Dimo",
        nms_descr: "",
        address1: "8020 Equestrian Ct,",
        address2: "",
        city: "Mentor",
        state: "OH",
        zip: "44060",
        zip4: "    ",
        phone: "2162100017",
        email: "pavllidimo@att.net",
        dateadded: "2006-09-27 12:47:05",
        addedby: null,
        lastchanged: "2020-09-22 09:14:30",
        lastchangedby: null,
        directions:
          "Discounted $60.00 for coffee machine; Misc. cost is glass block window and installation",
        callmorning: "0",
        callafternoon: "0",
        callevening: "0",
        callweekend: "0",
        dnc_id: " ",
        intdnc: " ",
        rev: "11",
        MailingAddress1: "",
        MailingAddress2: "",
        MailingCity: "(Unknown)",
        MailingState: "IL",
        MailingZip: "0",
        MailingZip4: "",
        Email2: "",
        cst_user_1: "",
        cst_user_2: "",
        cst_user_3: "",
        cst_user_4: "",
        cst_user_5: "",
        cst_user_6: null,
        cst_user_7: null,
        cst_user_8: null,
        cst_user_9: null,
        cst_user_10: null,
        cst_user_11: null,
        cst_user_12: null,
        cst_user_13: null,
        cst_user_14: null,
        cst_user_15: null,
        ils_productid: "Door",
        brn_id: "CLE",
        sds_id: "CLE",
        rnk_id: "1",
        apptdate: "2018-04-21 09:30:00",
        app_id: "179285",
        ils_slr_id: "875",
        ils_slr_id2: "0",
        ils_slr_split: null,
        dsp_id: "Sale",
        netissued: "1",
        sat: "1",
        sold: "1",
        gsa: "11400.0000",
        ils_prod1: "Door",
        qty1: "0.0000",
        gsa1: "11400.0000",
        ils_prod2: "",
        qty2: "0.0000",
        gsa2: "0.0000",
        ils_prod3: "",
        qty3: "0.0000",
        gsa3: "0.0000",
        ils_prod4: "",
        qty4: "0.0000",
        gsa4: "0.0000",
        ils_prod5: "",
        qty5: "0.0000",
        gsa5: "0.0000",
        ils_lastchangedby: "875",
        ils_lastchangedon: "2018-04-21 13:06:39",
        ils_lastchangedprogram: "Present.aspx",
        JobStatus: "Complete",
        CommissionType: "Standard Plan",
        InstallerName1: "Mader, Jim",
        InstallerName2: null,
        Finance1: "n/a",
        Finance2: "n/a",
        Finance3: "n/a",
        PaperworkStaus: "Received",
        MileStonePlanName: "Door",
        Grade: "",
        isBackLog: "0",
        MeasuredByName: "Mora, Rafael",
        SalesRepName1: "Frantz, Jake",
        SalesRepName2: "",
        Source: "Prior Customer",
        SubSource: "Cold Call",
        ActCompleteDate: "2018-07-27 00:00:00",
        ActCompleteTime: "",
        jsv_id: "26057",
        svs_id: "1",
        svc_id: "1",
        EnteredOnDate: "2018-09-20 14:27:54",
        partorderdate: null,
        EstArrivalDate: null,
        receiveddate: null,
        schedsvcdate: "2018-09-24 09:00:00",
        completedate: "2018-09-24 00:00:00",
        ponumber: "1240839",
        isbillable: "0",
        amountcharged: "0.0000",
        paidinfull: "0",
        assignedto: "909",
        ins_installer: "261",
        LastEditedOnDate: "2018-09-25 11:42:19",
        enteredby: "2363",
        lasteditedby: "2196",
        descr:
          "Front entry door water is leaking in the bottom and ruining the wood. Please assess and fix onsite if possible.",
        notes: "",
        parts: "",
        resolution: "",
        jsv_user_1: "",
        jsv_user_2: null,
        jsv_user_3: null,
        jsv_user_4: null,
        jsv_user_5: null,
        jsv_user_6: null,
        jsv_user_7: null,
        jsv_user_8: null,
        jsv_user_9: null,
        jsv_user_10: null,
        jsv_user_11: null,
        jsv_user_12: "0.0000",
        jsv_user_13: null,
        jsv_user_14: null,
        jsv_user_15: null,
        jsv_user_16: "0",
        jsv_user_17: "0",
        jsv_user_18: "0",
        jsv_user_19: "0",
        jsv_user_20: "0",
        ServiceStatus: "Complete",
        ServiceCategory: "Installation Problem",
        AssignedToName: "Morse, Ron",
        InstallerName: "Mader, Jim",
        EnteredByName: "Mitchell, Katie",
        LastEditedByName: "Branco, Courtney",
        LookupValueDescr16: "",
        LookupValueDescr17: "",
        LookupValueDescr18: "",
        LookupValueDescr19: "",
        LookupValueDescr20: ""
      },
      {
        id: "82987",
        lds_id: "511654",
        cst_id: "4113",
        ils_id: "193743",
        contractid: "413077",
        productid: "Windows",
        GrossAmount: "18600.0000",
        jbs_id: "C",
        brp_id: "CLE  ",
        pds_id: "CLE",
        cmt_id: "G",
        Commission: "283.9200",
        ins_installer1: "19",
        ins_installer2: "0",
        measuredby: "14",
        ContractDate: "2020-09-22 00:00:00",
        CancelDate: null,
        HoldDate: null,
        hld_id: " ",
        mls_id: "1",
        slr_id: "1084",
        slr_id2: "0",
        slr_split: "0",
        fns_id: " ",
        fns_id2: " ",
        fns_id3: " ",
        ProductID2: "-1",
        ProductID3: "",
        ProductID4: "",
        pws_id: "R",
        vnd_id: "0",
        vnd_id2: "0",
        vnd_id3: "0",
        vnd_id4: "0",
        GrossBatched: "0.0000",
        BatchFlag: "0",
        GrossBatched2: "0.0000",
        BatchFlag2: "0",
        StatusDate: "2021-02-18 00:00:00",
        BudgetCost: "0.0000",
        ActualCost: "0.0000",
        FundedDate: null,
        FundedAmount: "0.0000",
        ParAmount: "0.0500",
        FinCo_ID: "9",
        FinAmount: "13000.0000",
        FinMonths: "84",
        FinCrLimit: "18000.0000",
        FinPlan_ID: "7",
        FinApproved: "1",
        FinRate: "0",
        FinTerms: "84",
        FinExpire: "2021-01-20 00:00:00",
        FinFee: "0.0000",
        FinHomeValue: "0.0000",
        FinParty1Employer: "",
        FinParty1Income: "0.0000",
        FinParty1CreditScore: "0",
        FinParty1Name: "Pavlli Dimo",
        FinParty1EmpPhone: "",
        FinParty2Employer: "",
        FinParty2Income: "0.0000",
        FinParty2CreditScore: "0",
        FinParty2Name: "",
        FinParty2EmpPhone: "",
        FinDtApproved: "2020-09-22 00:00:00",
        job_user_1: null,
        job_user_2: "5000.00",
        job_user_3: null,
        job_user_4: null,
        job_user_5: "",
        job_user_6: null,
        job_user_7: null,
        job_user_8: null,
        job_user_9: null,
        job_user_10: null,
        job_user_11: null,
        job_user_12: null,
        job_user_13: null,
        job_user_14: null,
        job_user_15: null,
        job_user_16: "68",
        job_user_17: "67",
        job_user_18: "0",
        job_user_19: "0",
        job_user_20: null,
        LastModifiedBy: "2786",
        LastModifiedOn: "2021-02-18 13:07:14",
        USN: "39",
        JobNotes: "",
        FinNotes: "#####...",
        QBJobRefID: null,
        QBJobDate: null,
        QBJobBalance: null,
        ins_installer3: "0",
        ins_installer4: "0",
        JobNetAmt: "0.0000",
        nmp_descr: "Mr.",
        firstname: "Pavlli",
        lastname: "Dimo",
        nms_descr: "",
        address1: "8020 Equestrian Ct,",
        address2: "",
        city: "Mentor",
        state: "OH",
        zip: "44060",
        zip4: "    ",
        phone: "2162100017",
        email: "pavllidimo@att.net",
        dateadded: "2006-09-27 12:47:05",
        addedby: null,
        lastchanged: "2020-09-22 09:14:30",
        lastchangedby: null,
        directions:
          "Discounted $60.00 for coffee machine; Misc. cost is glass block window and installation",
        callmorning: "0",
        callafternoon: "0",
        callevening: "0",
        callweekend: "0",
        dnc_id: " ",
        intdnc: " ",
        rev: "11",
        MailingAddress1: "",
        MailingAddress2: "",
        MailingCity: "(Unknown)",
        MailingState: "IL",
        MailingZip: "0",
        MailingZip4: "",
        Email2: "",
        cst_user_1: "",
        cst_user_2: "",
        cst_user_3: "",
        cst_user_4: "",
        cst_user_5: "",
        cst_user_6: null,
        cst_user_7: null,
        cst_user_8: null,
        cst_user_9: null,
        cst_user_10: null,
        cst_user_11: null,
        cst_user_12: null,
        cst_user_13: null,
        cst_user_14: null,
        cst_user_15: null,
        ils_productid: "Windows",
        brn_id: "CLE",
        sds_id: "CLE",
        rnk_id: "4",
        apptdate: "2020-09-22 13:00:00",
        app_id: "358633",
        ils_slr_id: "1084",
        ils_slr_id2: "0",
        ils_slr_split: null,
        dsp_id: "Sale",
        netissued: "1",
        sat: "1",
        sold: "1",
        gsa: "18600.0000",
        ils_prod1: "Windows",
        qty1: "0.0000",
        gsa1: "18600.0000",
        ils_prod2: "",
        qty2: "0.0000",
        gsa2: "0.0000",
        ils_prod3: "",
        qty3: "0.0000",
        gsa3: "0.0000",
        ils_prod4: "",
        qty4: "0.0000",
        gsa4: "0.0000",
        ils_prod5: "",
        qty5: "0.0000",
        gsa5: "0.0000",
        ils_lastchangedby: "1084",
        ils_lastchangedon: "2020-09-22 14:24:44",
        ils_lastchangedprogram: "Present.aspx",
        JobStatus: "Complete",
        CommissionType: "Standard Plan",
        InstallerName1: "Tiffe, Joey",
        InstallerName2: null,
        Finance1: "n/a",
        Finance2: "n/a",
        Finance3: "n/a",
        PaperworkStaus: "Received",
        MileStonePlanName: "Window & Door Basic",
        Grade: "Reset",
        isBackLog: "0",
        MeasuredByName: "Muscovich, Walt",
        SalesRepName1: "Murphy, Mark",
        SalesRepName2: "",
        Source: "Google PPC",
        SubSource: "Search",
        ActCompleteDate: "2021-02-15 00:00:00",
        ActCompleteTime: null,
        jsv_id: "8",
        svs_id: "56199",
        svc_id: "5",
        EnteredOnDate: "0000-00-00 00:00:00",
        partorderdate: "2021-02-17 11:01:28",
        EstArrivalDate: null,
        receiveddate: null,
        schedsvcdate: null,
        completedate: "2021-03-03 09:00:00",
        ponumber: null,
        isbillable: "0",
        amountcharged: "0",
        paidinfull: "0",
        assignedto: "0",
        ins_installer: "3176",
        LastEditedOnDate: "0000-00-00 00:00:00",
        enteredby: "2021",
        lasteditedby: "3356",
        descr: "3356",
        notes: "4 damaged screens. re secreen.",
        parts: "",
        resolution: "",
        jsv_user_1: "",
        jsv_user_2: "",
        jsv_user_3: null,
        jsv_user_4: null,
        jsv_user_5: null,
        jsv_user_6: null,
        jsv_user_7: null,
        jsv_user_8: null,
        jsv_user_9: null,
        jsv_user_10: null,
        jsv_user_11: null,
        jsv_user_12: null,
        jsv_user_13: "0.0000",
        jsv_user_14: null,
        jsv_user_15: null,
        jsv_user_16: null,
        jsv_user_17: "0",
        jsv_user_18: "0",
        jsv_user_19: "0",
        jsv_user_20: "62",
        ServiceStatus: "0",
        ServiceCategory: "Service Scheduled",
        AssignedToName: "Installation Problem",
        InstallerName: "Fasciano, Ben",
        EnteredByName: "Fasciano, Ben",
        LastEditedByName: "Barnhard, Heather",
        LookupValueDescr16: "Barnhard, Heather",
        LookupValueDescr17: "",
        LookupValueDescr18: "",
        LookupValueDescr19: "",
        LookupValueDescr20: "Customer Service Team"
      }
    ],
    referrals: [
      // {
      //   ProspLeadID: "414295",
      //   custnumber: "373284",
      //   nmp_descr: "",
      //   firstname: "Kadee",
      //   lastname: "Anderson",
      //   nms_descr: "",
      //   Address1: "3428 Hi Land Park Dr",
      //   Address2: "",
      //   City: "De Soto",
      //   State: "MO",
      //   Zip: "63020",
      //   Zip4: "    ",
      //   Phone: "6362091755",
      //   Email: "kadee1755@gmail.com",
      //   DateAdded: "2020-02-04 09:01:13",
      //   AddedBy: null,
      //   LastChanged: "2020-02-05 08:03:56",
      //   Directions:
      //     "Couldn't tell if walls are 4 inch thick not normal siding on trailer or shingled roof",
      //   CallMorning: "0",
      //   CallAfternoon: "0",
      //   CallEvening: "0",
      //   CallWeekend: "0",
      //   dnc_id: " ",
      //   intdnc: " ",
      //   Rev: "6",
      //   MailingAddress1: "",
      //   MailingAddress2: "",
      //   MailingCity: "",
      //   MailingState: "  ",
      //   MailingZip: "",
      //   MailingZip4: "",
      //   Email2: "",
      //   cst_user_1: "",
      //   cst_user_2: "",
      //   cst_user_3: "",
      //   cst_user_4: "",
      //   cst_user_5: "",
      //   cst_user_6: null,
      //   cst_user_7: null,
      //   cst_user_8: null,
      //   cst_user_9: null,
      //   cst_user_10: null,
      //   cst_user_11: null,
      //   cst_user_12: null,
      //   cst_user_13: null,
      //   cst_user_14: null,
      //   cst_user_15: null,
      //   id: "427108",
      //   cst_id: "373284",
      //   LeadNumber: "427108",
      //   Productid: "Windows",
      //   Prod2: "",
      //   Prod3: "",
      //   Prod4: "",
      //   Qty: "4.0000",
      //   Qty2: "0.0000",
      //   Qty3: "0.0000",
      //   Qty4: "0.0000",
      //   EntryDate: "2020-02-04 00:00:00",
      //   dsp_id: "Set",
      //   val_ID: "1",
      //   pro_ID: "0",
      //   phn_ID: null,
      //   src_id: "Referral",
      //   brn_id: "STL",
      //   sds_id: "STL",
      //   rnk_id: "7",
      //   stg_id: "2",
      //   owner_id: "0",
      //   srs_id: "63",
      //   DateEntered: "2020-02-04 09:01:38",
      //   ApptDate: "2020-02-11 16:00:00",
      //   app_id: "300975",
      //   CallBackDate: null,
      //   CallBackEmp_id: null,
      //   slr_id: "0",
      //   slr_id2: "0",
      //   slr_split: null,
      //   SetBy: "2986",
      //   VerifiedBy: "0",
      //   ConfirmedBy: "0",
      //   ApptSet: "1",
      //   Verified: "0",
      //   Confirmed: "0",
      //   Issued: "0",
      //   NetIssued: "0",
      //   Sat: "0",
      //   Sold: "0",
      //   GSA: "0.0000",
      //   EverSet: "1",
      //   EverVerified: "0",
      //   EverConfirmed: "0",
      //   EverIssued: "0",
      //   EverNetIssued: "0",
      //   EverSat: null,
      //   LastChangedOn: "2020-02-05 08:03:56",
      //   LastChangedBy: "972",
      //   LastChangedProgram: "LeadDetail.aspx",
      //   Notes: "CTS \r\nReferral - Daniel Dashner #370059\r\nD. Kieschnick",
      //   clq_id: "0",
      //   cqd_id: "0",
      //   LastCall: "2020-03-05 13:44:10",
      //   LastResult: "NA",
      //   LogNumber: null,
      //   in1_id: null,
      //   work_order_id: null,
      //   DateReceived: null,
      //   ApptDuration: "0",
      //   FollowUpDate: null,
      //   lds_user_1: "0",
      //   lds_user_2: null,
      //   lds_user_3: "370059",
      //   lds_user_4: null,
      //   lds_user_5: null,
      //   lds_user_6: null,
      //   lds_user_7: "2020-02-04 00:00:00",
      //   lds_user_8: null,
      //   lds_user_9: null,
      //   lds_user_10: null,
      //   lds_user_11: null,
      //   lds_user_12: null,
      //   lds_user_13: null,
      //   lds_user_14: null,
      //   lds_user_15: null,
      //   lds_user_16: "0",
      //   lds_user_17: null,
      //   lds_user_18: null,
      //   lds_user_19: null,
      //   lds_user_20: null,
      //   deferdate: "2020-03-05 16:44:10",
      //   AddedByName: "",
      //   ValDescr: "",
      //   PromoterName: "",
      //   RankName: "Medial",
      //   OwnerName: "",
      //   SourceSubDescr: "Customer",
      //   SalesRepName: "",
      //   SalesRep2Name: "",
      //   SetByName: "Blackie, Samuel",
      //   VerifiedByName: "",
      //   ConfirmedByName: "",
      //   LastChangedByName: "Kerkan, Anthony",
      //   EmailRecdDate: null
      // },
      // {
      //   ProspLeadID: "414297",
      //   custnumber: "373286",
      //   nmp_descr: "",
      //   firstname: "Wally",
      //   lastname: "Moreland",
      //   nms_descr: "",
      //   Address1: "",
      //   Address2: "",
      //   City: "Saint Louis",
      //   State: "MO",
      //   Zip: "63146",
      //   Zip4: "    ",
      //   Phone: "2172991925",
      //   Email: "",
      //   DateAdded: "2020-02-04 09:04:48",
      //   AddedBy: null,
      //   LastChanged: "2020-02-04 09:05:01",
      //   Directions: "",
      //   CallMorning: "0",
      //   CallAfternoon: "0",
      //   CallEvening: "0",
      //   CallWeekend: "0",
      //   dnc_id: " ",
      //   intdnc: " ",
      //   Rev: "2",
      //   MailingAddress1: "",
      //   MailingAddress2: "",
      //   MailingCity: "",
      //   MailingState: "  ",
      //   MailingZip: "",
      //   MailingZip4: "",
      //   Email2: "",
      //   cst_user_1: "",
      //   cst_user_2: "",
      //   cst_user_3: "",
      //   cst_user_4: "",
      //   cst_user_5: "",
      //   cst_user_6: null,
      //   cst_user_7: null,
      //   cst_user_8: null,
      //   cst_user_9: null,
      //   cst_user_10: null,
      //   cst_user_11: null,
      //   cst_user_12: null,
      //   cst_user_13: null,
      //   cst_user_14: null,
      //   cst_user_15: null,
      //   id: "427109",
      //   cst_id: "373286",
      //   LeadNumber: "427109",
      //   Productid: "",
      //   Prod2: "",
      //   Prod3: "",
      //   Prod4: "",
      //   Qty: "0.0000",
      //   Qty2: "0.0000",
      //   Qty3: "0.0000",
      //   Qty4: "0.0000",
      //   EntryDate: "2020-02-04 00:00:00",
      //   dsp_id: "Data",
      //   val_ID: "1",
      //   pro_ID: "0",
      //   phn_ID: null,
      //   src_id: "Referral",
      //   brn_id: "STL",
      //   sds_id: "STL",
      //   rnk_id: "1",
      //   stg_id: "1",
      //   owner_id: "0",
      //   srs_id: "63",
      //   DateEntered: "2020-02-04 09:04:51",
      //   ApptDate: null,
      //   app_id: "300746",
      //   CallBackDate: null,
      //   CallBackEmp_id: null,
      //   slr_id: "0",
      //   slr_id2: "0",
      //   slr_split: null,
      //   SetBy: "0",
      //   VerifiedBy: "0",
      //   ConfirmedBy: "0",
      //   ApptSet: "0",
      //   Verified: "0",
      //   Confirmed: "0",
      //   Issued: "0",
      //   NetIssued: "0",
      //   Sat: "0",
      //   Sold: "0",
      //   GSA: "0.0000",
      //   EverSet: "0",
      //   EverVerified: "0",
      //   EverConfirmed: "0",
      //   EverIssued: "0",
      //   EverNetIssued: "0",
      //   EverSat: null,
      //   LastChangedOn: "2020-02-04 09:05:01",
      //   LastChangedBy: "2930",
      //   LastChangedProgram: "LeadDetail.aspx",
      //   Notes: "CTS \r\nReferral - Daniel Dashner #370059\r\nD. Kieschnick",
      //   clq_id: "0",
      //   cqd_id: "0",
      //   LastCall: "2020-02-13 09:09:06",
      //   LastResult: "NA",
      //   LogNumber: null,
      //   in1_id: null,
      //   work_order_id: null,
      //   DateReceived: null,
      //   ApptDuration: "0",
      //   FollowUpDate: null,
      //   lds_user_1: "0",
      //   lds_user_2: null,
      //   lds_user_3: "370059",
      //   lds_user_4: null,
      //   lds_user_5: null,
      //   lds_user_6: null,
      //   lds_user_7: null,
      //   lds_user_8: null,
      //   lds_user_9: null,
      //   lds_user_10: null,
      //   lds_user_11: null,
      //   lds_user_12: null,
      //   lds_user_13: null,
      //   lds_user_14: null,
      //   lds_user_15: null,
      //   lds_user_16: "0",
      //   lds_user_17: null,
      //   lds_user_18: null,
      //   lds_user_19: null,
      //   lds_user_20: null,
      //   deferdate: "2020-02-13 12:09:06",
      //   AddedByName: "",
      //   ValDescr: "",
      //   PromoterName: "",
      //   RankName: "",
      //   OwnerName: "",
      //   SourceSubDescr: "Customer",
      //   SalesRepName: "",
      //   SalesRep2Name: "",
      //   SetByName: "",
      //   VerifiedByName: "",
      //   ConfirmedByName: "",
      //   LastChangedByName: "Basista, Maureen",
      //   EmailRecdDate: null
      // }
    ]
  },
  getters: {
    logged: state => {
      return state.logged;
    },
    projects: state => {
      return state.projects;
    },
    CUSTOMERS: state => {
      return state.customer;
    }
  },
  mutations: {
    SET_PROJECTS(state, payload) {
      state.projects = payload.projects;
    },
    SET_SERVICES(state, payload) {
      state.services = payload.services;
    },
    SET_REFERRALS(state, payload) {
      state.referrals = payload.referrals;
    },
    SET_CUSTOMER(state, payload) {
      state.customer = payload.customer;
    },
    SET_LOGIN(state, logged) {
      state.logged = logged;
    }
  },
  actions: {
    loadProjects({ commit }) {
      Vue.Axios.post("portal", {})
        .then(result => {
          commit("SET_PROJECTS", result.data);
        })
        .catch(error => {
          throw new Error(`API ${error}`);
        });
    },
    setLogin({ commit }, status) {
      commit("SET_LOGIN", status ? true : false);
    },
    LOAD_PORTAL: async (context, request) => {
      let { data } = await Axios.post(
        "https://aaronbeach.pythonanywhere.com/portal",
        request
      );
      console.log(data);
      context.commit("SET_CUSTOMER", data);
      context.commit("SET_PROJECTS", data);
      // context.commit("SET_SERVICES", data);
      context.commit("SET_REFERRALS", data);
    }
  },
  modules: {}
});
